Vagrant.configure("2") do |config|
  config.vm.define "dev-ubuntu-vbox"

  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider :virtualbox do |vbox|
    vbox.cpus = 2
    vbox.memory = 4096
  end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yaml"
  end
  config.vm.synced_folder "~/repos/", "/home/vagrant/shared/"
end
