#!/bin/bash

set -eu

echo 'Creating home py venv'

PY_DIR=${HOME}/.python/
cd $PY_DIR
echo $(pwd)

if [ -d venv ]; then
  echo 'Removing existing venv dir'
  rm -r venv
fi

echo 'Creating venv'
python3 -m venv venv

echo 'Activating venv'
source ${HOME}/.python/venv/bin/activate

echo 'Installing packages'
pip3 install --upgrade pip
pip3 install -r ${HOME}/.python/requirements.txt

