# Preinstall
# 1. Install curl, ollama
#    ```
#    sudo apt update
#    sudo apt install --yes curl
#    curl -fsSL https://ollama.com/install.sh | sh
#    ```
# 2. Install docker
#     ```
#     ansible-playbook ~/.playbooks/common/docker.yaml -i ~/.playbooks/inventory.yaml --ask-become-pass --limit ubuntu
#     ```
---
- hosts: servers
  tasks:
    - name: Mount disk
      when: inventory_hostname in groups['ubuntu']
      become: true
      ansible.posix.mount:
        path: /media/
        src: /dev/sda1
        fstype: ext4
        state: mounted
        opts: defaults
    - name: Create ollama dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/apps/ollama/
    - name: Create ollama dirs
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/systemd/system/ollama.service.d/
    - name: Write ollama systemd
      become: true
      ansible.builtin.copy:
        dest: /etc/systemd/system/ollama.service.d/override.conf
        content: |
          [Service]
          Environment="OLLAMA_HOST=0.0.0.0"
          Environment="OLLAMA_ORIGINS=http://desktop.local:3000"
          Environment="OLLAMA_MODELS=/media/rick/ollama"
    - name: Start ollama server
      become: true
      ansible.builtin.systemd_service:
        name: ollama.service
        enabled: false
        state: restarted
    - name: Write ollama docker compose
      ansible.builtin.copy:
        dest: ~/apps/ollama/docker-compose.yaml
        content: |
          ---
          services:
            chromadb:
              image: ghcr.io/chroma-core/chroma:latest
              restart: always
              ports:
                - 8000:8000
              environment:
                IS_PERSISTENT: TRUE
              extra_hosts:
                - "host.docker.internal:host-gateway"
              volumes:
                - ./chromadb:/chroma/chroma/
            n8n:
              image: docker.n8n.io/n8nio/n8n
              restart: always
              ports:
                - 5678:5678
              environment:
                N8N_CONCURRENCY_PRODUCTION_LIMIT: 8
                N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
                N8N_HOST: desktop.local
                N8N_PORT: 5678
                N8N_RUNNERS_ENABLED: true
                N8N_SECURE_COOKIE: false
                NODE_ENV: production
                WEBHOOK_URL: http://desktop.local:5678/
                GENERIC_TIMEZONE: UTC
              volumes:
                - ./n8n/data:/home/node/.n8n
                - ./n8n/files:/files
            postgres:
              image: pgvector/pgvector:pg18-trixie
              restart: always
              ports:
                - 5432:5432
              extra_hosts:
                - "host.docker.internal:host-gateway"
              environment:
                POSTGRES_HOST_AUTH_METHOD: trust
              volumes:
                - ./pgdata:/var/lib/postgresql
            redis:
              image: redis/redis-stack-server:latest
              restart: always
              ports:
                - 6379:6379
              extra_hosts:
                - "host.docker.internal:host-gateway"
              volumes:
                - ./redis:/data
            ui:
              image: jakobhoeg/nextjs-ollama-ui
              restart: always
              extra_hosts:
                - "host.docker.internal:host-gateway"
              environment:
                OLLAMA_URL: http://desktop.local:11434
              ports:
                - 8080:3000
    - name: Create, start ollama
      community.docker.docker_compose_v2:
        project_src: ~/apps/ollama/
