#!/bin/bash

set -exo pipefail

git fetch --all

if [ -z "$2" ]; then
  date="$(date +"%Y%m%d")"
  suffix="$(head -c 2 /dev/urandom | hexdump -e '2/1 "%02x"')"
  git checkout -b "rbetzler/${date}-${suffix}" $1
else
  git checkout -b "rbetzler/${2}" $1
fi
