#!/bin/bash

set -exo pipefail

if [[ $1 == "primary" ]]; then
  branch=$(git b-primary)
else
  branch="$1"
fi

git checkout "$branch"

git pull

if [ -z "$2" ]; then
  date="$(date +"%Y%m%d")"
  suffix="$(head -c 2 /dev/urandom | hexdump -e '2/1 "%02x"')"
  git checkout -b "rbetzler/${date}-${suffix}"
else
  git checkout -b "rbetzler/${2}"
fi
