#!/bin/bash

set -exo pipefail

if [[ $1 == "primary" ]]; then
  branch="origin/$(git b-primary)"
else
  branch="$1"
fi

git fetch --all

if [ -z "$2" ]; then
  date="$(date +"%Y%m%d")"
  suffix="$(head -c 2 /dev/urandom | hexdump -e '2/1 "%02x"')"
  git checkout -b "rbetzler/${date}-${suffix}" $branch
else
  git checkout -b "rbetzler/${2}" $branch
fi
