#!/bin/bash

set -eo pipefail

gh_arg=""
if [[ "$1" == 0 ]]; then
  arg='all'
elif [[ "$1" == 1 ]]; then
  arg='me'
  gh_arg="--author @me"
elif [[ "$1" == 2 ]]; then
  arg='team'
fi

python $HOME/.git_aliases/parse_gh.py $arg "$(gh pr list $gh_arg --json 'author,number,state,isDraft,title,url' --limit 1000)"
