#!/bin/bash

set -euxo pipefail

if [ "$1" == "draft" ]; then
  draft_arg="--draft"
else
  draft_arg=""
fi

if [ "$2" == "" ]; then
  branch_arg=""
else
  branch_arg="--base $2"
fi

current_branch=$(git branch --show-current)

# If reopening pr, close out the existing one
if [ "$3" == "reopen" ]; then

  gh pr create --fill $draft_arg $branch_arg 2>/tmp/prs || true
  url=$(cat /tmp/prs | grep http)
  pr_number=$(echo ${url##*/})
  gh pr close $pr_number
  gh pr create --fill $draft_arg $branch_arg

# Otherwise, just print the logs
else

  git psu
  pr=$(gh pr create --fill $draft_arg $branch_arg --head $current_branch)
  copyq copy "$pr"

fi
