#!/bin/bash

set -euo pipefail
branch=$(git b-current)

# If no arg provided
if [[ $# -eq 0 ]]; then
  target=${1:-$(git b-primary)}
else
  target=$1
fi

git co "$target"
git pl
git co "$branch"
git rb "$target"
