#!/bin/bash

set -euxo pipefail

feature=$(git b-current)

if [[ $# -eq 0 ]]; then
  base_branch=$(git b-primary)
else
  base_branch="$1"
fi

my_first_commit=$(git cherry "$base_branch" "$feature" | head -1 | cut -d' ' -f2)

head_commit=$(git rev-parse "$my_first_commit"^1)

git rebase -i "$head_commit"

