#!/bin/bash

sth="$(git stash list | fzf --preview 'git stash show $(echo {} | awk "{print substr(\$1, 1, length(\$1)-1)}") -p --color=always' \
  --bind 'F8:execute(git stash drop $(echo {} | awk "{print substr(\$1, 1, length(\$1)-1)}") > /dev/null)+reload(git stash list)')"

if [ "$sth" == "" ]; then
  echo 'No selection'
  exit 0
else
  git stash apply "$(echo "$sth" | awk '{print substr($1, 1, length($1)-1)}')"
fi
