Vagrant.configure("2") do |config|
  config.vm.define "dev-clickhouse"
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "~/repos/ClickHouse", "/home/vagrant/shared"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    sudo apt-get update -y
    sudo apt-get install -y \
      build-essential \
      git \
      cmake \
      ccache \
      python3 \
      ninja-build \
      nasm \
      yasm \
      gawk \
      lsb-release \
      wget \
      software-properties-common \
      gnupg

    sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  SHELL
end
