Vagrant.configure("2") do |config|
  config.vm.define "dev-clickhouse"

  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider :libvirt do |lv|
    lv.cpus = 2
    lv.cpu_mode = "host-passthrough"
    lv.disk_bus = "virtio"
    lv.disk_driver :cache => "writeback"
    lv.memory = 4096
    lv.nic_model_type = "virtio"
    lv.video_type = "vga"
    lv.video_vram = 1024
  end

  config.vm.synced_folder "~/repos/ClickHouse", "/home/vagrant/shared"
  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    sudo apt-get update -y
    sudo apt-get install -y \
      build-essential \
      git \
      cmake \
      ccache \
      python3 \
      ninja-build \
      nasm \
      yasm \
      gawk \
      lsb-release \
      wget \
      software-properties-common \
      gnupg

    sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  SHELL
end
