#!/bin/bash


dbt-comp-model()
{
  dbt compile -m "$1"
  top_dir="$(git rev-parse --show-toplevel)"
  dbt_dir="$(fdfind dbt --type d "$top_dir")"
  file="$(fdfind --type f --full-path "$dbt_dir" --no-ignore | fzf --query "target compiled $1" --select-1)"
  batcat "$file"
}
