#!/bin/bash

dkrm-all(){
  docker rm $(docker ps -aq)
}

dkrmi-all(){
  docker rmi $(docker images -q)
}

alias dkb="docker build"
alias dke="docker exec -it"
alias dki="docker images"
alias dkpl="docker pull"
alias dkps="docker ps"
alias dkpsa="docker ps -a"
alias dkpsaq="docker ps -aq"
alias dkrm="docker rm"
alias dkrmf="docker rm -f"
alias dkrmi="docker rmi"
alias dkrmif="docker rmi -f"
alias dkr="docker run"
alias dkrit="docker run -it"
alias dkstp="docker stop"
alias dks="docker start"
