#!/bin/bash

alias dki="docker images"
alias dkps="docker ps"
alias dkpsa="docker ps -a"
alias dkrm="docker rm"
alias dkrmf="docker rm -f"
alias dkrmi="docker rmi"
alias dkrn="docker run"
alias dkrnit="docker run -it"
alias dks="docker stop"
