#!/bin/bash

dkrm-all(){
  docker rm $(docker ps -aq)
}

dkrmf-all(){
  docker rm -f $(docker ps -aq)
}

dkrmi-all(){
  docker rmi $(docker images -q)
}

dkrmif-all(){
  docker rmi -f $(docker images -q)
}

dkstp-all(){
  docker stop $(docker ps -q)
}

dkstp-rm-rmi-all(){
  docker stop $(docker ps -aq)
  dkrm-all
  dkrmi-all
}

alias dkb="docker build"
alias dke="docker exec -it"
alias dki="docker images"
alias dkk="docker kill"
alias dkpl="docker pull"
alias dkps="docker ps"
alias dkpsa="docker ps -a"
alias dkpsaq="docker ps -aq"
alias dkrm="docker rm"
alias dkrmf="docker rm -f"
alias dkrmi="docker rmi"
alias dkrmif="docker rmi -f"
alias dkr="docker run"
alias dkrit="docker run -it"
alias dkstp="docker stop"
alias dks="docker start"

alias mk="minikube"
alias k="kubectl"

# Load kubectl autocomplete
kk(){
  source <(kubectl completion zsh)
  source <(helm completion zsh)
}
