#!/bin/bash

# This script sets up mbsync for gmail

setup_isync_mailboxes(){
  set -eux pipefail

  # Create and enter mutt dir
  cd $HOME
  mkdir -p .mutt
  cd .mutt

  for f in ~/.creds_mutt/*; do

    # Ignore readme file
    if [ "${f: -3}" != ".md" ]; then

      # For every mutt credentials file,
      # create a user dir
      source "$f"
      mkdir -p $MUTT_USER
      mkdir -p "$MUTT_USER/inbox"

      # Copy template file if it has been updated
      cp -u ~/.mbsyncrc "$MUTT_USER/.mbsyncrc"

      # Replace user name, password placeholders in the rc file
      sd 'MY_USER' "$MUTT_USER" "$MUTT_USER/.mbsyncrc"
      sd 'MY_PWD' "$MUTT_PWD" "$MUTT_USER/.mbsyncrc"
      sd 'MY_EMAIL_ADDR' "$MUTT_EMAIL_ADDR" "$MUTT_USER/.mbsyncrc"

    fi

  done

  set +eux pipefail
}
