#!/bin/bash

set -euxo pipefail

# Read a little bit of everything
sites="
https://www.npr.org
https://www.wsj.com
https://www.nytimes.com
https://www.msnbc.com
https://www.cnn.com/
https://www.foxnews.com/
https://www.gzeromedia.com
https://www.bloomberg.com
https://www.ft.com
https://www.economist.com
https://www.nypost.com
https://www.oann.com
https://www.newsmax.com
https://www.democracynow.org
https://www.currentaffairs.org
https://www.slate.com/
https://www.theintercept.com/
https://www.aljazeera.com
https://www.thedailybeast.com
https://www.jacobinmag.com
"

PS3="Enter a number: "

select site in $sites
do
  echo "Selected: $site"
  vivaldi "$site" &> /dev/null &
  exit 0
done
