#!/bin/bash

sync_current_mailbox(){
  echo $MUTT_USER
  mbsync -a -c ~/.mutt/"$MUTT_USER"/.mbsyncrc
}

# Sync all mutt mailboxes
sync_all_mailboxes(){
  for d in ~/.mutt/*; do
    echo $d
    mbsync -a -c "$d/.mbsyncrc"
  done
}
