#!/bin/bash

# Run vgrep but discard the output
# Then start an interactive vgrep session
ivgrep()
{
  vgrep "$1" > /dev/null
  vgrep --interactive
}

# Do not exclude gitignored directories
ivgrep-all()
{
  vgrep --no-index "$1" > /dev/null
  vgrep --interactive
}

# Remove entire line from file
# by writing to a new file
# then moving it back
remove_line(){
    files=$(grep -rl "$1" .)
    if [ -z "$files" ]; then
      echo "Pattern not found: $1"
      echo "In file: $2"
    else
      grep -vwE "$1" "$2" > "$2".tmp
      mv "$2".tmp "$2"
    fi
}
