---
- hosts: localhost
  connection: local
  tasks:
    - name: Load gnome config desktop environment
      ansible.builtin.shell: |
        dconf load / < "${HOME}/.desktop.conf"
    - name: Set default shell to zsh
      become: true
      ansible.builtin.command: usermod --shell /usr/bin/zsh {{ ansible_env.USER }}
      changed_when: false
    # These likely exist, but leaving this just in case
    # - name: Creates oh my zsh directories
    #   ansible.builtin.file:
    #     state: directory
    #     path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item }}/"
    #   loop:
    #     - plugins
    #     - themes
    - name: Link themes
      ansible.builtin.file:
        src: '{{ ansible_env.HOME }}/repos/oh-my-zsh-extensions/themes/zsh/dracula.zsh-theme'
        dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/dracula.zsh-theme'
        state: link
    - name: Link plugins
      ansible.builtin.file:
        src: '{{ ansible_env.HOME }}/repos/oh-my-zsh-extensions/plugins/{{ item }}'
        dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item }}'
        state: link
      loop:
        - fzf-tab
        - nix-zsh-completions
        - zsh-autosuggestions
        - zsh-nix-shell
        - zsh-syntax-highlighting
        - zsh-system-clipboard
        - zsh-vi-mode
    # - name: Check for neovim plugins
    #   register: nvim_plugins
    #   ansible.builtin.stat:
    #     path: '{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim'
    # - name: Install vim plug for neovim plugins
    #   when: nvim_plugins.stat.isreg is not defined
    #   ansible.builtin.shell: |
    #     sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    #       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    # - name: Install, update neovim plugins
    #   ansible.builtin.shell: |
    #     nvim --headless +PlugInstall +qa
    #     nvim --headless +UpdateRemotePlugins +qa
    - name: List all zen profiles
      register: zen_profiles
      ansible.builtin.find:
        paths: '{{ ansible_env.HOME }}/.zen/'
        recurse: false
        file_type: directory
    - name: Link user.js
      ansible.builtin.file:
        src: '{{ ansible_env.HOME }}/.config/rlb/zen/user.js'
        dest: '{{ item }}/user.js'
        state: link
      with_items: "{{ zen_profiles.files | map(attribute='path') | list }}"
    - name: Install local proxy globally
      become: true
      ignore_errors: true
      community.general.npm:
        name: local-ssl-proxy
        executable: '{{ ansible_env.HOME }}/.nvm/versions/node/v24.1.0/bin/npm'
        global: true
