---
- hosts: localhost
  connection: local
  vars_files:
    - ./variables.yaml
  tasks:
    - name: Install nix
      when: include_nix
      become: true
      community.general.pacman:
        state: present
        name: nix
    - name: Add user to nix group
      when: include_nix
      become: true
      ansible.builtin.user:
        name: '{{ ansible_env.USER }}'
        group: nix-users
    - name: Enable, start nix service
      when: include_nix
      become: true
      ansible.builtin.systemd_service:
        name: nix-daemon.service
        enabled: true
        state: started
    # Requires reboot
    - name: Enable nix socket
      when: include_nix
      become: true
      block:
        - name: Enable nix socket
          ansible.builtin.systemd_service:
            name: nix-daemon.socket
            enabled: true
            # state: started
      rescue:
        - fail:
            msg: Reboot required on new install, do so manually
    - name: Check for nix channel
      when: include_nix
      changed_when: false
      register: nix_channel
      ansible.builtin.shell: |
        export LD_LIBRARY_PATH=''
        if nix-channel --list | grep -q unstable ; then
          echo installed
        else
          echo not-installed
        fi
    - name: Install nix channel
      when:
        - include_nix
        - nix_channel.stdout == "not-installed"
      ansible.builtin.shell: |
        export LD_LIBRARY_PATH=''
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
    - name: Update nix channel
      when: include_nix
      block:
        - name: Update nix channel
          ansible.builtin.shell: |
            export LD_LIBRARY_PATH=''
            nix-channel --update
      rescue:
        - fail:
            msg: >
              Cannot update nix channel while in nix shell,
              exit nix shell then retry
    - name: Check for nix shell caching
      when: include_nix
      changed_when: false
      register: nix_shell
      ansible.builtin.shell: |
        export LD_LIBRARY_PATH=''
        if nix-env -qa --installed "*" | grep -q cache ; then
          echo installed
        else
          echo not-installed
        fi
    - name: Install nix shell caching
      when:
        - include_nix
        - nix_shell.stdout == "not-installed"
      ansible.builtin.shell: |-
        export LD_LIBRARY_PATH=''
        nix-env -iA nixpkgs.cached-nix-shell
