---
- hosts: localhost
  connection: local
  tasks:
    - name: Install python venv
      ansible.builtin.pip:
        virtualenv: "{{ ansible_env.HOME }}/venv"
        requirements: "{{ ansible_env.HOME }}/requirements.txt"
