---
- hosts: localhost
  connection: local
  vars_files:
    - ./variables.yaml
  tasks:
    - name: Install global requirements
      become: true
      community.general.pacman:
        state: present
        name:
          - git
          - ghostty
          - less
          - neovim
          - python
          - python-pip
          - python-virtualenv
          - terminator
          - wget
          - zsh
    - name: Install hyprland, etc
      become: true
      community.general.pacman:
        state: present
        name:
          - blueman
          - brightnessctl
          - cava
          - hyprland
          - hyprlock
          - hyprpaper
          - hyprsunset
          - network-manager-applet
          - pavucontrol
          - rofi
          - swaync
          - waybar
          - xdg-desktop-portal-hyprland
    - name: Install aesthetic helpers
      become: true
      community.general.pacman:
        state: present
        name:
          - nerd-fonts
          - gnome-themes-extra
          - gnome-tweaks
    - name: Install cli tooling
      become: true
      community.general.pacman:
        state: present
        name:
          - bat
          - dysk
          - eza
          - fd
          - fzf
          - gawk
          - git-delta
          - glow
          - graphviz
          - htop
          - jq
          - pwgen
          - sd
          - unzip
          - yazi
          - go-yq
    - name: Install xorg (for zoom mainly)
      become: true
      community.general.pacman:
        state: present
        name: xorg-server
    - name: Install shells and shell tools
      become: true
      community.general.pacman:
        state: present
        name:
          - fish
          - starship
    - name: Install other apps
      become: true
      community.general.pacman:
        state: present
        name:
          - act
          - age
          - argocd
          - aws-cli
          - bc
          - bind
          - bitwarden-cli
          - copyq
          - dbeaver
          - direnv
          - dpkg
          - github-cli
          - gparted
          - helm
          - kubectl
          - libreoffice-still
          # Extra req for uv
          - libxcrypt-compat
          - minikube
          - mise
          # - mysql
          - ncspot
          - networkmanager-openvpn
          # - nodejs
          - nvm
          - obsidian
          - ollama
          - openvpn
          - pandoc-cli
          - pgcli
          - pulumi
          - pyenv
          - rpi-imager
          - sops
          - tk
          - tree
          # - usage
          - uv
          - whois
          - xclip
          - yarn
          # - ydotool
    - name: Install audio
      become: true
      community.general.pacman:
        state: present
        name:
          - pipewire
          - pipewire-alsa
          - pipewire-audio
          - pipewire-pulse
          - sof-firmware
    - name: Install bluetooth
      become: true
      community.general.pacman:
        state: present
        name:
          - bluez
          - bluez-utils
    - name: Enable, start bluetooth
      become: true
      ansible.builtin.systemd_service:
        name: bluetooth.service
        state: started
        enabled: true
    - name: Enable, start time sync
      become: true
      ansible.builtin.systemd_service:
        name: systemd-timesyncd.service
        enabled: true
        state: started
    # - name: Enable, start ydotool
    #   ansible.builtin.systemd_service:
    #     name: ydotool
    #     enabled: true
    #     scope: user
    #     state: started
    - name: Install browsers
      become: true
      community.general.pacman:
        state: present
        name:
          - brave-bin
          - chromium
          - firefox
    - name: Create the `aur_builder` user
      become: true
      ansible.builtin.user:
        name: aur_builder
        create_home: true
        group: wheel
    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: true
        mode: 0644
        validate: visudo -cf %s
    - name: Install yay using makepkg
      kewlfft.aur.aur:
        name: yay
        use: makepkg
        state: present
        local_pkgbuild: '{{ ansible_env.HOME }}/repos/yay-bin'
    - name: Install common apps
      kewlfft.aur.aur:
        use: yay
        name:
          - slack-desktop
          - spotify
          - zoom
    - name: Install work cli tooling
      kewlfft.aur.aur:
        use: yay
        name:
          - google-cloud-cli
          - google-cloud-cli-gke-gcloud-auth-plugin
          # - jira-cli
          # - opencode-bin
    - name: Install dracula aesthetics
      kewlfft.aur.aur:
        use: yay
        name:
          - dracula-gtk-theme
          - dracula-icons-git
    - name: Install hardware helpers
      kewlfft.aur.aur:
        use: yay
        name:
          - zramswap
    - name: Install cli tooling
      kewlfft.aur.aur:
        use: yay
        name:
          - argo-bin
          - autojump-rs
          - clickhouse
          - tre-command
          - vgrep
    - name: Install ventoy
      kewlfft.aur.aur:
        use: yay
        name:
          - ventoy-bin
    - name: Install hyprland extras
      kewlfft.aur.aur:
        use: yay
        name:
          - hyprland-monitor-attached
          - hyprshot
    # - name: Install kanata
    #   kewlfft.aur.aur:
    #     use: yay
    #     name:
    #       - kanata-bin
