---
- hosts: localhost
  connection: local
  tasks:
    - name: Generate zsh autocompletes
      ansible.builtin.shell: |
        {{ item }} completion zsh > "${HOME}/.utils/{{ item }}.zsh"
      loop:
        - argo
        - argocd
        - fnox
        - helm
        - kind
        - kubectl
        - mise
        - pulumi
    - name: Check for autocomplete for autojump
      register: autocomplete_autojump
      ansible.builtin.stat:
        path: '{{ ansible_env.HOME }}/.local/share/autojump/autojump.zsh'
    - name: Copy autocomplete for autojump
      when: autocomplete_autojump.stat.isreg is not defined
      ansible.builtin.shell: |
        mkdir -p "${HOME}/.local/share/autojump/"
        cp $(find / -name autojump.zsh 2> /dev/null | head -n 1) "${HOME}/.local/share/autojump/autojump.zsh"
