---
- hosts: localhost
  connection: local
  tasks:
    - name: Check for nvm install
      register: nvm_plugins
      ansible.builtin.stat:
        path: '{{ ansible_env.HOME }}/.nvm/versions/node/v24.1.0/bin/npm'
    - name: Install node
      when: nvm_plugins.stat.isreg is not defined
      ansible.builtin.shell: |
        source /usr/share/nvm/init-nvm.sh
        nvm install 24.1.0
    - name: Install local proxy globally
      become: true
      ignore_errors: true
      community.general.npm:
        name: local-ssl-proxy
        executable: '{{ ansible_env.HOME }}/.nvm/versions/node/v24.1.0/bin/npm'
        global: true
