---
- hosts: localhost
  connection: local
  tasks:
    - name: Set default shell to zsh
      become: true
      ansible.builtin.command: usermod --shell /usr/bin/zsh {{ ansible_env.USER }}
      changed_when: false
