[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
SOPS_AGE_KEY_FILE = "~/.config/sops/age/keys.txt"
FNOX_AGE_KEY_FILE = "~/.config/sops/age/keys.txt"

BUILDX_BAKE_ENTITLEMENTS_FS = "0"
FNOX_SHELL_OUTPUT = "none"

[tools]
fnox = "latest"
usage = "latest"
